<?php
/**
 * Plugin adapter for YayCurrency - WooCommerce Multi-Currency Switcher.
 * Generated by yaycommerce-init. Edit values as needed.
 */

defined( 'ABSPATH' ) || exit;

class YayCurrencyPluginAdapter implements \YayCurrencyScoped\YayCommerce\AdminShell\Contracts\PluginMenuAdapter {
	public function get_menu_title(): string {
		return 'YayCurrency'; }
	public function get_page_title(): string {
		return 'YayCurrency - WooCommerce Multi-Currency Switcher'; }
	public function get_menu_slug(): string {
		return 'yay-currency-settings'; }
	public function get_settings_page_callback(): ?callable {
		return static function (): void {
			?>
			<div id="yay-currency"></div>
			<?php
		}; } // Set your render callback here
	public function get_settings_page_position(): ?int {
		return 140; }
	public function get_capability(): string {
		return 'manage_woocommerce'; }
	public function get_plugin_basename(): string {
		return YAY_CURRENCY_BASE_NAME; }
	public function get_settings_label(): string {
		return 'Settings'; }
	public function get_docs_url(): string {
		return 'https://docs.yaycommerce.com/yaycurrency/'; }
	public function get_pro_url(): string {
		return 'https://yaycommerce.com/yaycurrency-woocommerce-multi-currency-switcher/'; }
}
